# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{analytics_pusher}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["tpitale"]
  s.date = %q{2010-06-08}
  s.description = %q{Simple, Rails 3 gem with a jQuery UJS "driver" to permit pushing analytics forward on redirect
to the next page rendered. Also includes url helpers link/button/mail _to with options for
virtual pageview or event tracking.}
  s.email = %q{tpitale@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "lib/analytics_pusher.rb",
     "lib/analytics_pusher/actions.rb",
     "lib/analytics_pusher/form_helpers.rb",
     "lib/analytics_pusher/helpers.rb",
     "lib/analytics_pusher/rails.rb",
     "lib/analytics_pusher/url_helpers.rb",
     "lib/generators/pusher/pusher_generator.rb",
     "lib/generators/pusher/templates/analytics_pusher.js",
     "test/helper.rb",
     "test/test_analytics_pusher.rb"
  ]
  s.homepage = %q{http://github.com/tpitale/analytics_pusher}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Push create/edit/destroy forward to be tracked as pageviews}
  s.test_files = [
    "test/helper.rb",
     "test/test_analytics_pusher.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

